library(shiny)
library(activityinfo)
library(httr2)
library(dplyr)
library(stringr)
library(bslib)
library(gridlayout)
library(DT)
library(waiter)
library(readxl)
library(writexl)
library(purrr)

list.files("R", pattern = "\\.R$", full.names = TRUE) |> walk(source)
source("global.R")
source("ui.R")
source("server.R")

rsconnect::writeManifest()
shinyApp(ui = ui, server = server)
