library(shiny)
library(writexl)
library(activityinfo)
library(bslib)
library(gridlayout)
library(DT)
library(purrr)
rsconnect::writeManifest()
credentials <- Sys.getenv("ACTIVITYINFOTOKEN")
activityInfoToken(credentials, prompt = FALSE)
shinyApp(ui = ui, server = server)
